<a href="https://colab.research.google.com/github/Chanunchida-May/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

###Numpy Array

สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก 

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (Zeros,ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix randoom

In [10]:
np.random.randn(5,5) # randoom เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-1.98043290e+00,  1.17992326e+00, -1.09531313e+00,
         1.78015850e-03,  6.68845479e-01],
       [-3.67623324e-01, -1.01128319e+00,  2.15366590e+00,
        -6.96069981e-01, -3.28520996e-01],
       [-1.01971225e+00,  4.44836183e-01,  1.22023549e+00,
        -1.22127465e+00, -1.49499800e+00],
       [ 9.02914999e-03,  3.19898261e-02, -1.24600024e+00,
         1.27138403e+00,  6.91575528e-01],
       [ 9.47289734e-01, -8.46772723e-01,  4.54300433e-01,
         1.38756038e+00,  5.19360803e-01]])

In [11]:
2 + (5*np.random.randn(3,3)) # randoom เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 0.01288593, 11.65331496,  9.73985261],
       [ 7.09748814,  8.9536648 ,  4.55880808],
       [-1.28753608,  1.12130125,  8.60279192]])

In [12]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4,5)

array([[ 5, 10,  7,  6,  9],
       [ 5,  7,  6,  8,  7],
       [ 8,  8, 10, 10, 10],
       [ 9, 10,  6,  8,  8]])